---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This feature was introduced in Kustomization 5.0 to control order
sortOptions:
  order: fifo
resources:
  - namespace.yaml
  - subscription.yaml
  - operatorgroup.yaml
  - ./automation-controller/
