apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  finalizers:
  - finalizers.fluxcd.io
  name: customer-deployment
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./ansible-automation-platform/
  prune: true
  sourceRef:
    kind: GitRepository
    name: customer-deployment
