apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  labels:
    app.kubernetes.io/component: automationcontroller
    app.kubernetes.io/managed-by: automationcontroller-operator
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: automation-controller
  name: automation-controller
  namespace: ansible-automation-platform
spec:
  admin_user: admin
  auto_upgrade: true
  create_preload_data: true
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled
  ee_images:
  - image: registry.redhat.io/ansible-automation-platform-24/ee-cloud-services-rhel8:latest
    name: ee-cloud-services
  - image: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
    name: ee-29-compatible
  - image: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
    name: ee-minimal
  - image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
    name: ee-supported
  ee_pull_credentials_secret: automation-controller-ee-pull-credentials
  extra_settings:
  - setting: AWX_RUNNER_KEEPALIVE_SECONDS
    value: 240
  - setting: SUBSCRIPTION_USAGE_MODEL
    value: '""'
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  image_pull_secrets:
  - redhat-operators-pull-secret
  ingress_type: none
  ipv6_disabled: false
  loadbalancer_ip: ""
  loadbalancer_port: 80
  loadbalancer_protocol: http
  no_log: true
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  security_context_settings:
    runAsGroup: 0
    runAsUser: 1000
  set_self_labels: true
  task_privileged: false
  termination_grace_period_seconds: 600
