apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: automation-hub
  namespace: ansible-automation-platform
spec:
  container_token_secret: aaphub-token
  file_storage_access_mode: ReadWriteMany
  file_storage_size: 100Gi
  gunicorn_api_workers: 2
  gunicorn_content_workers: 2
  gunicorn_timeout: 90
  haproxy_timeout: 180s
  image_pull_policy: IfNotPresent
  image_pull_secrets:
  - redhat-operators-pull-secret
  ingress_type: none
  loadbalancer_port: 80
  loadbalancer_protocol: http
  nginx_client_max_body_size: 10m
  nginx_proxy_connect_timeout: 120s
  nginx_proxy_read_timeout: 120s
  nginx_proxy_send_timeout: 120s
  no_log: true
  object_storage_azure_secret: automation-hub-object-storage
  pulp_settings:
    analytics: false
    ansible_api_hostname: https://hub.aapjfri6q2uqpuwi.az.ansiblecloud.com
    connected_ansible_controllers:
    - https://controller.aapjfri6q2uqpuwi.az.ansiblecloud.com
    content_origin: https://hub.aapjfri6q2uqpuwi.az.ansiblecloud.com
    galaxy_collection_signing_service: ""
    galaxy_container_signing_service: ""
    private_key_path: /etc/pulp/keys/container_auth_private_key.pem
    public_key_path: /etc/pulp/keys/container_auth_public_key.pem
    redirect_to_object_storage: "False"
    token_auth_disabled: "False"
    token_server: https://hub.aapjfri6q2uqpuwi.az.ansiblecloud.com/token/
    token_signature_algorithm: ES256
  route_tls_termination_mechanism: Edge
  storage_type: Azure
  worker:
    replicas: 2
    resource_requirements:
      limits:
        memory: 5Gi
