apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: ansible-controller
  namespace: ansible-automation-platform
spec:
  hostname: test.apps.rosa.dhageman-hcp.guj9.p3.openshiftapps.com
  route_host: test.apps.rosa.dhageman-hcp.guj9.p3.openshiftapps.com
